In [48]:
import numpy as np


In [49]:
mu1, sigma1 = 0, 1
mu2, sigma2 = 0, 0.5

rng1 = np.random.default_rng(2021)
rng2 = np.random.default_rng(2022)

a1 = rng1.normal(mu1, sigma1, size=(1000, 10000))
a2 = rng1.normal(mu2, sigma2, size=(50, 10000))
# array = np.random.normal(3, 2.5, size=(100, 1000))

In [50]:
train_ds = tf.data.Dataset.from_tensor_slices(
    (a1, a1)).shuffle(10000).batch(32)
test_ds = tf.data.Dataset.from_tensor_slices((a2, a2)).batch(32)

In [51]:
for x in train_ds.take(1):
    print(x)

(<tf.Tensor: shape=(32, 10000), dtype=float64, numpy=
array([[ 0.58807706,  1.12288687,  2.49332294, ..., -0.98990713,
         2.01846207, -0.27202634],
       [-0.68907428, -0.40466232,  2.20483952, ...,  0.43943435,
        -0.51860075, -0.45000514],
       [-2.05099966, -0.65171295, -0.51995008, ...,  0.32529135,
        -0.24688654,  0.0899967 ],
       ...,
       [ 1.14983847,  0.65151296, -0.17824972, ...,  1.55349213,
        -1.19902922, -0.21721015],
       [ 0.84529065,  0.29849664, -0.7382579 , ...,  1.27014916,
         0.00354616,  0.20478834],
       [-0.78006098, -1.44359769,  0.0558797 , ...,  0.83345165,
        -2.13012123,  0.58448947]])>, <tf.Tensor: shape=(32, 10000), dtype=float64, numpy=
array([[ 0.58807706,  1.12288687,  2.49332294, ..., -0.98990713,
         2.01846207, -0.27202634],
       [-0.68907428, -0.40466232,  2.20483952, ...,  0.43943435,
        -0.51860075, -0.45000514],
       [-2.05099966, -0.65171295, -0.51995008, ...,  0.32529135,
        -0.24

In [52]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import tensorflow as tf

from sklearn.metrics import accuracy_score, precision_score, recall_score
from sklearn.model_selection import train_test_split
from tensorflow.keras import layers, losses
from tensorflow.keras.datasets import fashion_mnist
from tensorflow.keras.models import Model


In [73]:
latent_dim = 128 

class Autoencoder(Model):
  def __init__(self):
    super(Denoise, self).__init__()
    self.encoder = tf.keras.Sequential([
    tf.keras.layers.Dense(124, activation=tf.nn.relu, input_shape=(10000,)),  # input shape required
    tf.keras.layers.Dense(64, activation=tf.nn.relu)
    ])

    self.decoder = tf.keras.Sequential([
    tf.keras.layers.Dense(64, activation=tf.nn.relu),  # input shape required
    tf.keras.layers.Dense(128, activation=tf.nn.relu),
    tf.keras.layers.Dense(1000)
    ])

  def call(self, x):
    encoded = self.encoder(x)
    decoded = self.decoder(encoded)
    return decoded

In [54]:
# # latent_dim = 128 

# class Autoencoder(Model):
#   def __init__(self, latent_dim):
#     super(Autoencoder, self).__init__()
#     self.latent_dim = latent_dim   
#     self.encoder = tf.keras.Sequential([
#       layers.Flatten(),
#       layers.Dense(latent_dim, activation='relu'),
#     ])
#     self.decoder = tf.keras.Sequential([
#       layers.Dense(10000, activation='sigmoid'),
#     ])

#   def call(self, x):
#     encoded = self.encoder(x)
#     decoded = self.decoder(encoded)
#     return decoded

# # autoencoder = Autoencoder(latent_dim)

In [76]:
# autoencoder.compile(optimizer='adam', loss=losses.MeanSquaredError())

In [77]:
# autoencoder.fit(train_ds,
#                 epochs=10,
#                 shuffle=True,
#                 validation_data=test_ds)

In [80]:
features, labels = next(iter(train_ds))

In [81]:
print(features)
print(labels)

tf.Tensor(
[[-1.63219276 -0.37784733  0.236585   ... -0.12561019  0.07560304
  -1.06040727]
 [ 0.60626003 -1.59534899 -0.86375106 ... -0.63657414  0.02946459
   1.02662489]
 [ 0.9731796   0.84495496  0.56769243 ...  1.20538453  2.05864566
  -0.40382469]
 ...
 [ 1.31078288 -0.55284671 -1.01449893 ... -0.30489861  1.22010635
   0.39076648]
 [-2.11813488 -1.60475061 -0.49969536 ... -0.13612149  0.76678184
   0.14736664]
 [ 0.4843778  -0.76054873 -0.55190128 ... -1.36003154 -0.0580185
   1.45220198]], shape=(32, 10000), dtype=float64)
tf.Tensor(
[[-1.63219276 -0.37784733  0.236585   ... -0.12561019  0.07560304
  -1.06040727]
 [ 0.60626003 -1.59534899 -0.86375106 ... -0.63657414  0.02946459
   1.02662489]
 [ 0.9731796   0.84495496  0.56769243 ...  1.20538453  2.05864566
  -0.40382469]
 ...
 [ 1.31078288 -0.55284671 -1.01449893 ... -0.30489861  1.22010635
   0.39076648]
 [-2.11813488 -1.60475061 -0.49969536 ... -0.13612149  0.76678184
   0.14736664]
 [ 0.4843778  -0.76054873 -0.55190128 ... 

In [82]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(124, activation=tf.nn.relu, input_shape=(10000,)),  # input shape required
    tf.keras.layers.Dense(64, activation=tf.nn.relu),
    
    tf.keras.layers.Dense(64, activation=tf.nn.relu),
    tf.keras.layers.Dense(10000),
])

In [83]:
predictions = model(features)
predictions[:1]

<tf.Tensor: shape=(1, 10000), dtype=float32, numpy=
array([[ 0.01334581, -0.035305  ,  0.00326403, ...,  0.03380992,
         0.04189924,  0.07051864]], dtype=float32)>

In [84]:
model.compile(optimizer='adam', loss=losses.MeanSquaredError())

In [85]:
model.fit(train_ds,
                epochs=500,
                shuffle=True)

Epoch 1/500
32/32 [==============================] - 1s 15ms/step - loss: 1.0014
Epoch 2/500
32/32 [==============================] - 0s 14ms/step - loss: 1.0003
Epoch 3/500
32/32 [==============================] - 0s 14ms/step - loss: 0.9976
Epoch 4/500
32/32 [==============================] - 1s 16ms/step - loss: 0.9909
Epoch 5/500
32/32 [==============================] - 1s 16ms/step - loss: 0.9823
Epoch 6/500
32/32 [==============================] - 1s 16ms/step - loss: 0.9760
Epoch 7/500
32/32 [==============================] - 1s 17ms/step - loss: 0.9692
Epoch 8/500
32/32 [==============================] - 1s 18ms/step - loss: 0.9630
Epoch 9/500
32/32 [==============================] - 1s 17ms/step - loss: 0.9587
Epoch 10/500
32/32 [==============================] - 1s 16ms/step - loss: 0.9543
Epoch 11/500
32/32 [==============================] - 1s 17ms/step - loss: 0.9517
Epoch 12/500
32/32 [==============================] - 1s 16ms/step - loss: 0.9493
Epoch 13/500
32/32 [=====

32/32 [==============================] - 0s 15ms/step - loss: 0.9361
Epoch 102/500
32/32 [==============================] - 0s 15ms/step - loss: 0.9358
Epoch 103/500
32/32 [==============================] - 0s 14ms/step - loss: 0.9351
Epoch 104/500
32/32 [==============================] - 1s 15ms/step - loss: 0.9350
Epoch 105/500
32/32 [==============================] - 0s 14ms/step - loss: 0.9352
Epoch 106/500
32/32 [==============================] - 0s 14ms/step - loss: 0.9350
Epoch 107/500
32/32 [==============================] - 0s 15ms/step - loss: 0.9346
Epoch 108/500
32/32 [==============================] - 1s 16ms/step - loss: 0.9345
Epoch 109/500
32/32 [==============================] - 1s 16ms/step - loss: 0.9343
Epoch 110/500
32/32 [==============================] - 1s 16ms/step - loss: 0.9343
Epoch 111/500
32/32 [==============================] - 1s 16ms/step - loss: 0.9342
Epoch 112/500
32/32 [==============================] - 1s 16ms/step - loss: 0.9344
Epoch 113/500
32/3

32/32 [==============================] - 1s 17ms/step - loss: 0.9308
Epoch 298/500
32/32 [==============================] - 1s 17ms/step - loss: 0.9308
Epoch 299/500
32/32 [==============================] - 1s 16ms/step - loss: 0.9309
Epoch 300/500
32/32 [==============================] - 1s 17ms/step - loss: 0.9318
Epoch 301/500
32/32 [==============================] - 0s 15ms/step - loss: 0.9312
Epoch 302/500
32/32 [==============================] - 1s 16ms/step - loss: 0.9314
Epoch 303/500
32/32 [==============================] - 0s 14ms/step - loss: 0.9314
Epoch 304/500
32/32 [==============================] - 1s 16ms/step - loss: 0.9316
Epoch 305/500
32/32 [==============================] - 1s 15ms/step - loss: 0.9318
Epoch 306/500
32/32 [==============================] - 0s 15ms/step - loss: 0.9321
Epoch 307/500
32/32 [==============================] - 1s 16ms/step - loss: 0.9319
Epoch 308/500
32/32 [==============================] - 1s 16ms/step - loss: 0.9322
Epoch 309/500
32/3

32/32 [==============================] - 1s 17ms/step - loss: 0.9301
Epoch 494/500
32/32 [==============================] - 1s 16ms/step - loss: 0.9300
Epoch 495/500
32/32 [==============================] - 1s 16ms/step - loss: 0.9301
Epoch 496/500
32/32 [==============================] - 1s 15ms/step - loss: 0.9302
Epoch 497/500
32/32 [==============================] - 0s 15ms/step - loss: 0.9302
Epoch 498/500
32/32 [==============================] - 1s 16ms/step - loss: 0.9304
Epoch 499/500
32/32 [==============================] - 1s 16ms/step - loss: 0.9305
Epoch 500/500
32/32 [==============================] - 1s 16ms/step - loss: 0.9306


In [87]:
loss_object = tf.keras.losses.MeanSquaredError()

In [88]:
def loss(model, x, y, training):
  # training=training is needed only if there are layers with different
  # behavior during training versus inference (e.g. Dropout).
    y_ = model(x, training=training)

    return loss_object(y_true=y, y_pred=y_)

l = loss(model, features, labels, training=False)
print("Loss test: {}".format(l))

Loss test: 0.913756787776947
